version: '3'

services:
    node:
        container_name: riott-api
        build: .
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development # Define o host, controla a exibição de logs e execução de migrations
            - PORT=8080
            - MONGO_CONNECTION_URL=mongodb://riott_root:55a716fe3d2053ed61b16948@riott-mongo:27017
        networks:
            - riott-connect
        links:
            - mongo
        ports:
            - 4444:8080

    # Banco com MongoDB
    mongo:
        container_name: riott-mongo
        restart: always
        image: mongo
        command: [--auth]
        volumes:
            - ~/docker/volumes/RIOTT_MongoDB:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: riott_root
            MONGO_INITDB_ROOT_PASSWORD: 55a716fe3d2053ed61b16948
        networks:
            - riott-connect
        ports:
            - 27017:27017
        logging:
            driver: none # Habilitar para visualizar as queries do banco

volumes:
    riott-node-data:
    riott-mongo-data:

networks:
    riott-connect:
        driver: bridge
